### ISSUE TITLE
Number of Edges not working

### ISSUE THREAD

**Issue by Adam7557** [rostam/GraphTea#55]
Reports>General>Number_Of_Edges 
seems to not work properly and gives way more edges than exist. I think this might be an issue when multiple edges and vertices have been created and deleted.

Heres the stack trace that the program told me to include:

graphtea.library.exceptions.InvalidVertexException: You are trying to access or use a vertex that does not exist:Invalid
	at graphtea.library.ListGraph.checkVertex(Unknown Source)
	at graphtea.library.ListGraph.getEdges(Unknown Source)
	at graphtea.library.ListGraph.isEdge(Unknown Source)
	at graphtea.graph.graph.GraphModel.insertEdge(Unknown Source)
	at graphtea.plugins.main.core.actions.edge.AddEdge.doJob(Unknown Source)
	at graphtea.plugins.main.core.actions.edge.AddEdge.performAction(Unknown Source)
	at graphtea.platform.core.AbstractAction.keyChanged(Unknown Source)
	at graphtea.platform.core.BlackBoard.fireListeners(Unknown Source)
	at graphtea.platform.core.BlackBoard.setData(Unknown Source)
	at graphtea.graph.graph.FastRenderer.ActionPerformed(Unknown Source)
	at graphtea.graph.graph.GraphControl.sendEventToBlackBoard(Unknown Source)
	at graphtea.graph.graph.GraphControl.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by rostam** [comment]
@Adam7557 I think this should not be an issue now. I will close this.
